### ISSUE TITLE
Menu expands on bottom instead of upwards if it is placed on bottom of the screen. See screenshot for difference. 

### ISSUE THREAD

**Issue by takasurazeem** [hdehghan/EasyMenu#2]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/2876680/228657116-e1acd092-8779-4971-a224-d6ff1778b050.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/2876680/228657148-23708620-3a71-41cc-a659-8c4da0de4c42.png">

**Comment by aumchauhan** [comment]
I have addressed the issue (#2) by fixing the menu expansion direction. A pull request #4 has been submitted for review.
